### ISSUE TITLE
Removing t3ver_* columns causes error

### ISSUE THREAD

**Issue by maximaexchen** [oliverklee/workshop-handouts#91]
I removed the columns set by Extension Builder. 
Then I get the Error, when calling showAction (findAll) in Controller:
Oops, an error occurred! Unknown column 'tx_extension_domain_model_object.t3ver_state' in 'where clause'

Do I have to remove any references, too?
Missed I something important to do?

**Comment by oliverklee** [comment]
Did you also remove it from the TCA and the table definition?

**Comment by maximaexchen** [comment]
Do I have to set 'versioningWS' => true, to false?
Missed that

**Comment by oliverklee** [comment]
Yes, that's needed as well.

Would you be willing to create a PR to add this to the handout?

**Comment by maximaexchen** [comment]
Sure I would.
But I am new to git and I do not not how to add a pull request correctly.
I try to figure it out.

**Comment by oliverklee** [comment]
Great!

And if you need help, please feel free to ask.

**Comment by oliverklee** [comment]
Some tutorials concerning forks and pull requests:
https://guides.github.com/activities/forking/
https://help.github.com/articles/syncing-a-fork/
https://help.github.com/articles/about-pull-requests/

**Comment by maximaexchen** [comment]
Ok thanks.

**Comment by maximaexchen** [comment]
So. I made a fork and committed the update.
You may look before I "pull-request" something stupid:
https://github.com/maximaexchen/workshop-handouts/blob/master/extbase-best-practices/sql-tca.tex

**Comment by oliverklee** [comment]
Looks most generally (and there's also no shame in directly creating a PR and then doing the discussion there).
A few things:

- I strongly propose you put your changes in branches so you can have more than one pull request (and a clean master).
- Please move the .gitignore change to a separate PR.
- Please format versioningWS, false and the table name with texttt.

**Comment by oliverklee** [comment]
Fixed by ffdb432e2fe1119c3fb774ec8e558a1140afa71f.
